[workspace]
members = ["leptos_hotkeys", "examples/demo", "examples/ssr-demo"]
resolver = "2"

[workspace.dependencies]
wasm-bindgen = "0.2"
web-sys = "0.3"


[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
