[config]
default_to_workspace = false

[tasks.lint]
description = "Check format of files and run linters"
run_task = { name = ["lint-rs"] }

[tasks.lint-rs]
description = "Lint Rust code"
run_task = { name = ["clippy", "cargo-check", "format-check"] }

[tasks.clippy]
clear = true
description = "Run clippy"
run_task = { name = [
    "clippy-no-features",
    "clippy-debug",
    "clippy-ssr"
] }

# TODO: Remove ["-W", "clippy::empty-docs"] when the next issue is resolved:
# https://github.com/leptos-rs/leptos/issues/2406
[tasks.clippy-no-features]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-Dwarnings", "-A", "clippy::empty-docs"]

[tasks.clippy-debug]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--features=debug", "--", "-Dwarnings", "-A", "clippy::empty-docs"]

[tasks.clippy-ssr]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--features=ssr", "--", "-Dwarnings", "-A", "clippy::empty-docs"]

[tasks.cargo-check]
clear = true
description = "Run cargo-check"
run_task = { name = [
    "cargo-check-no-features",
    "cargo-check-debug",
    "cargo-check-ssr"
] }

[tasks.cargo-check-no-features]
command = "cargo"
args = ["check"]

[tasks.cargo-check-debug]
command = "cargo"
args = ["check", "--features=debug"]

[tasks.cargo-check-ssr]
command = "cargo"
args = ["check", "--features=ssr"]

[tasks.format-check]
description = "Check Rust code formatting with rustfmt"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.format]
clear = true
description = "Format files"
run_task = { name = ["format-rs"] }

[tasks.format-rs]
description = "Format Rust code with rustfmt"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]
