[package]
name = "leptos_hotkeys"
version = "0.1.6"
edition = "2021"
description = "A library that declaratively pairs keybindings with callbacks for Leptos applications."
license = "MIT"
repository = "http://github.com/friendlymatthew/leptos-hotkeys"
readme = "README.md"
authors = ["Matthew Kim", "Alvaro Mondejar", "Robert Junkins"]
keywords = ["leptos", "hotkeys", "wasm"]

[dependencies]
leptos = { version = "0.6.5", features = ["nightly"] }
wasm-bindgen = { version = "0.2.92" }
log = "0.4.20"
web-sys = { version = "0.3.66" }

[lib]
name = "leptos_hotkeys"
path = "src/lib.rs"

[features]
debug = []
ssr = []
